### ISSUE TITLE
您好，请问下这个是萤石视频的接入吗

### ISSUE THREAD

**Issue by lixinxiaobai** [raininfall/react-native-ys#1]
这个是萤石的接入吗，支持android和ios双版本吗？

**Comment by raininfall** [comment]
是的。
只做了Android，只有播放部分，验证码也没做，欢迎PR。

**Comment by lixinxiaobai** [comment]
编译apk之后，app打不开， 一打开就报错"已停止运行" ...是什么原因

**Comment by raininfall** [comment]
信息太少，无法推断。

**Comment by lixinxiaobai** [comment]
额，就是因为不知道啥原因， 打开就闪退了。。  不知道应该在哪调试，编译的时候也没报错
最主要的是我不懂android原生 T_T
你这里都安装的时候都一切正常吗

**Comment by raininfall** [comment]
我这里是正常的。
如果可以的话吧代码建个库，我看下。

**Comment by lixinxiaobai** [comment]
闪退是我这边的原因，应该是我这边模拟器和手机的原因， 但是我又重新搞了下，就用你的这个demo出错了， 报错信息是 Could not invoke YS.initLib
我这边的地址是[https://github.com/lixinxiaobai/ys-demo](url)，不过和你的demo代码是一样一样的

**Comment by raininfall** [comment]
萤石的Android不支持X86平台，所以模拟器不能用。

**Comment by raininfall** [comment]
你正常安装，demo的工程是本地开发测试用的，依赖在本地。
```bash
yarn add react-native-ys
react-native link react-native-ys
```

**Comment by raininfall** [comment]
demo的package.json中
```json
"dependencies": {
		"react": "~15.4.0",
		"react-native": "0.41.2",
                "react-native-ys": "..."
	},
```
这个在上一层文件夹中找依赖，自然找不到

**Comment by lekenny** [comment]
有没有 ios 版本的啊

**Comment by raininfall** [comment]
本人iOS能力有限，近期做不了。欢迎PR
